2021-01-31 19:30:10,570:INFO:PyCaret Supervised Module
2021-01-31 19:30:10,570:INFO:ML Usecase: classification
2021-01-31 19:30:10,570:INFO:version 2.2.3
2021-01-31 19:30:10,570:INFO:Initializing setup()
2021-01-31 19:30:10,571:INFO:setup(target=Label, ml_usecase=classification, available_plots={'parameter': 'Hyperparameters', 'auc': 'AUC', 'confusion_matrix': 'Confusion Matrix', 'threshold': 'Threshold', 'pr': 'Precision Recall', 'error': 'Prediction Error', 'class_report': 'Class Report', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'calibration': 'Calibration Curve', 'vc': 'Validation Curve', 'dimension': 'Dimensions', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'boundary': 'Decision Boundary', 'lift': 'Lift Chart', 'gain': 'Gain Chart', 'tree': 'Decision Tree'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=simple, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=None, numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=False, normalize_method=zscore, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=False, multicollinearity_threshold=0.9, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=False, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=False, fold_strategy=stratifiedkfold, fold=10, fold_shuffle=False, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=123, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2021-01-31 19:30:10,571:INFO:Checking environment
2021-01-31 19:30:10,571:INFO:python_version: 3.8.5
2021-01-31 19:30:10,571:INFO:python_build: ('default', 'Jul 28 2020 12:59:40')
2021-01-31 19:30:10,571:INFO:machine: x86_64
2021-01-31 19:30:10,669:INFO:platform: Linux-5.4.0-64-generic-x86_64-with-glibc2.29
2021-01-31 19:30:10,671:INFO:Memory: svmem(total=20866641920, available=13759725568, percent=34.1, used=5977980928, free=7376879616, active=6736060416, inactive=5330231296, buffers=598261760, cached=6913519616, shared=1008001024, slab=507072512)
2021-01-31 19:30:10,674:INFO:Physical Core: 4
2021-01-31 19:30:10,675:INFO:Logical Core: 8
2021-01-31 19:30:10,675:INFO:Checking libraries
2021-01-31 19:30:10,675:INFO:pd==1.1.5
2021-01-31 19:30:10,675:INFO:numpy==1.19.0
2021-01-31 19:30:10,676:INFO:sklearn==0.23.2
2021-01-31 19:30:12,958:INFO:xgboost==1.2.1
2021-01-31 19:30:12,958:INFO:lightgbm==3.1.1
2021-01-31 19:30:13,012:INFO:catboost==0.24.4
2021-01-31 19:30:15,483:INFO:mlflow==1.13.1
2021-01-31 19:30:15,483:INFO:Checking Exceptions
2021-01-31 19:30:15,484:INFO:Declaring global variables
2021-01-31 19:30:15,484:INFO:USI: eccd
2021-01-31 19:30:15,484:INFO:pycaret_globals: {'USI', 'logging_param', 'gpu_param', '_all_models', 'prep_pipe', 'log_plots_param', 'imputation_classifier', '_internal_pipeline', 'n_jobs_param', 'exp_name_log', 'pycaret_globals', 'transform_target_method_param', '_all_metrics', 'fold_generator', 'create_model_container', 'html_param', 'y', 'imputation_regressor', '_available_plots', 'stratify_param', 'fix_imbalance_param', 'iterative_imputation_iters_param', 'fold_param', '_ml_usecase', 'fold_shuffle_param', 'y_train', 'display_container', 'y_test', '_gpu_n_jobs_param', '_all_models_internal', 'X', 'X_test', 'master_model_container', 'data_before_preprocess', 'target_param', 'seed', 'experiment__', 'fold_groups_param', 'transform_target_param', 'X_train', 'fix_imbalance_method_param'}
2021-01-31 19:30:15,484:INFO:Preparing display monitor
2021-01-31 19:30:15,484:INFO:Preparing display monitor
2021-01-31 19:30:15,512:INFO:Importing libraries
2021-01-31 19:30:15,513:INFO:Copying data for preprocessing
2021-01-31 19:30:15,650:INFO:Declaring preprocessing parameters
2021-01-31 19:30:15,868:INFO:Creating preprocessing pipeline
2021-01-31 19:30:20,031:INFO:Preprocessing pipeline created successfully
2021-01-31 19:30:20,031:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2021-01-31 19:30:20,031:INFO:Creating global containers
2021-01-31 19:30:20,052:INFO:Internal pipeline: Pipeline(memory=None, steps=[('empty_step', 'passthrough')], verbose=False)
2021-01-31 19:31:33,526:INFO:Creating grid variables
2021-01-31 19:31:33,930:INFO:create_model_container: 0
2021-01-31 19:31:33,930:INFO:master_model_container: 0
2021-01-31 19:31:33,931:INFO:display_container: 1
2021-01-31 19:31:33,945:INFO:Pipeline(memory=None,
         steps=[('dtypes',
                 DataTypes_Auto_infer(categorical_features=[],
                                      display_types=True, features_todrop=[],
                                      id_columns=[],
                                      ml_usecase='classification',
                                      numerical_features=[], target='Label',
                                      time_features=[])),
                ('imputer',
                 Simple_Imputer(categorical_strategy='not_available',
                                fill_value_categorical=None,
                                fill_value_numerical=None,
                                numeric_strate...
                ('scaling', 'passthrough'), ('P_transform', 'passthrough'),
                ('binn', 'passthrough'), ('rem_outliers', 'passthrough'),
                ('cluster_all', 'passthrough'),
                ('dummy', Dummify(target='Label')),
                ('fix_perfect', Remove_100(target='Label')),
                ('clean_names', Clean_Colum_Names()),
                ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                ('dfs', 'passthrough'), ('pca', 'passthrough')],
         verbose=False)
2021-01-31 19:31:33,945:INFO:setup() succesfully completed......................................
2021-01-31 19:32:46,599:INFO:Initializing compare_models()
2021-01-31 19:32:46,599:INFO:compare_models(include=None, fold=None, round=4, cross_validation=True, sort=Accuracy, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, verbose=True, display=None, exclude=None)
2021-01-31 19:32:46,599:INFO:Checking exceptions
2021-01-31 19:32:46,605:INFO:Preparing display monitor
2021-01-31 19:32:46,605:INFO:Preparing display monitor
2021-01-31 19:32:46,656:INFO:Initializing Logistic Regression
2021-01-31 19:32:46,656:INFO:Total runtime is 4.192193349202474e-06 minutes
2021-01-31 19:32:46,675:INFO:SubProcess create_model() called ==================================
2021-01-31 19:32:46,676:INFO:Initializing create_model()
2021-01-31 19:32:46,676:INFO:create_model(estimator=lr, fold=StratifiedKFold(n_splits=10, random_state=123, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7f1a03afa2e0>, kwargs={})
2021-01-31 19:32:46,677:INFO:Checking exceptions
2021-01-31 19:32:46,677:INFO:Importing libraries
2021-01-31 19:32:46,677:INFO:Copying training dataset
2021-01-31 19:32:46,741:INFO:Defining folds
2021-01-31 19:32:46,741:INFO:Declaring metric variables
2021-01-31 19:32:46,758:INFO:Importing untrained model
2021-01-31 19:32:46,777:INFO:Logistic Regression Imported succesfully
2021-01-31 19:32:46,823:INFO:Starting cross validation
2021-01-31 19:32:46,825:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=123, shuffle=False), n_jobs=-1
2021-01-31 19:33:23,771:INFO:Calculating mean and std
2021-01-31 19:33:23,777:INFO:Creating metrics dataframe
2021-01-31 19:33:23,801:INFO:Uploading results into container
2021-01-31 19:33:23,802:INFO:Uploading model into container now
2021-01-31 19:33:23,802:INFO:create_model_container: 1
2021-01-31 19:33:23,803:INFO:master_model_container: 1
2021-01-31 19:33:23,803:INFO:display_container: 2
2021-01-31 19:33:23,805:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2021-01-31 19:33:23,806:INFO:create_model() succesfully completed......................................
2021-01-31 19:33:24,226:INFO:SubProcess create_model() end ==================================
2021-01-31 19:33:24,227:INFO:Creating metrics dataframe
2021-01-31 19:33:24,269:INFO:Initializing K Neighbors Classifier
2021-01-31 19:33:24,269:INFO:Total runtime is 0.6268890778223674 minutes
2021-01-31 19:33:24,294:INFO:SubProcess create_model() called ==================================
2021-01-31 19:33:24,295:INFO:Initializing create_model()
2021-01-31 19:33:24,295:INFO:create_model(estimator=knn, fold=StratifiedKFold(n_splits=10, random_state=123, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7f1a03afa2e0>, kwargs={})
2021-01-31 19:33:24,296:INFO:Checking exceptions
2021-01-31 19:33:24,296:INFO:Importing libraries
2021-01-31 19:33:24,296:INFO:Copying training dataset
2021-01-31 19:33:24,360:INFO:Defining folds
2021-01-31 19:33:24,360:INFO:Declaring metric variables
2021-01-31 19:33:24,382:INFO:Importing untrained model
2021-01-31 19:33:24,411:INFO:K Neighbors Classifier Imported succesfully
2021-01-31 19:33:24,453:INFO:Starting cross validation
2021-01-31 19:33:24,455:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=123, shuffle=False), n_jobs=-1
2021-01-31 19:34:49,761:INFO:Calculating mean and std
2021-01-31 19:34:49,763:INFO:Creating metrics dataframe
2021-01-31 19:34:49,780:INFO:Uploading results into container
2021-01-31 19:34:49,780:INFO:Uploading model into container now
2021-01-31 19:34:49,780:INFO:create_model_container: 2
2021-01-31 19:34:49,780:INFO:master_model_container: 2
2021-01-31 19:34:49,781:INFO:display_container: 2
2021-01-31 19:34:49,782:INFO:KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
2021-01-31 19:34:49,782:INFO:create_model() succesfully completed......................................
2021-01-31 19:34:50,168:INFO:SubProcess create_model() end ==================================
2021-01-31 19:34:50,168:INFO:Creating metrics dataframe
2021-01-31 19:34:50,225:INFO:Initializing Naive Bayes
2021-01-31 19:34:50,227:INFO:Total runtime is 2.0595154325167337 minutes
2021-01-31 19:34:50,260:INFO:SubProcess create_model() called ==================================
2021-01-31 19:34:50,262:INFO:Initializing create_model()
2021-01-31 19:34:50,263:INFO:create_model(estimator=nb, fold=StratifiedKFold(n_splits=10, random_state=123, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7f1a03afa2e0>, kwargs={})
2021-01-31 19:34:50,263:INFO:Checking exceptions
2021-01-31 19:34:50,263:INFO:Importing libraries
2021-01-31 19:34:50,263:INFO:Copying training dataset
2021-01-31 19:34:50,335:INFO:Defining folds
2021-01-31 19:34:50,335:INFO:Declaring metric variables
2021-01-31 19:34:50,363:INFO:Importing untrained model
2021-01-31 19:34:50,395:INFO:Naive Bayes Imported succesfully
2021-01-31 19:34:50,441:INFO:Starting cross validation
2021-01-31 19:34:50,444:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=123, shuffle=False), n_jobs=-1
2021-01-31 19:34:56,014:INFO:Calculating mean and std
2021-01-31 19:34:56,017:INFO:Creating metrics dataframe
2021-01-31 19:34:56,036:INFO:Uploading results into container
2021-01-31 19:34:56,037:INFO:Uploading model into container now
2021-01-31 19:34:56,037:INFO:create_model_container: 3
2021-01-31 19:34:56,038:INFO:master_model_container: 3
2021-01-31 19:34:56,038:INFO:display_container: 2
2021-01-31 19:34:56,039:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2021-01-31 19:34:56,039:INFO:create_model() succesfully completed......................................
2021-01-31 19:34:56,504:INFO:SubProcess create_model() end ==================================
2021-01-31 19:34:56,504:INFO:Creating metrics dataframe
2021-01-31 19:34:56,563:INFO:Initializing Decision Tree Classifier
2021-01-31 19:34:56,563:INFO:Total runtime is 2.1651250680287677 minutes
2021-01-31 19:34:56,587:INFO:SubProcess create_model() called ==================================
2021-01-31 19:34:56,588:INFO:Initializing create_model()
2021-01-31 19:34:56,589:INFO:create_model(estimator=dt, fold=StratifiedKFold(n_splits=10, random_state=123, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7f1a03afa2e0>, kwargs={})
2021-01-31 19:34:56,589:INFO:Checking exceptions
2021-01-31 19:34:56,589:INFO:Importing libraries
2021-01-31 19:34:56,589:INFO:Copying training dataset
2021-01-31 19:34:56,657:INFO:Defining folds
2021-01-31 19:34:56,657:INFO:Declaring metric variables
2021-01-31 19:34:56,693:INFO:Importing untrained model
2021-01-31 19:34:56,734:INFO:Decision Tree Classifier Imported succesfully
2021-01-31 19:34:56,787:INFO:Starting cross validation
2021-01-31 19:34:56,789:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=123, shuffle=False), n_jobs=-1
2021-01-31 19:36:16,518:INFO:Calculating mean and std
2021-01-31 19:36:16,521:INFO:Creating metrics dataframe
2021-01-31 19:36:16,544:INFO:Uploading results into container
2021-01-31 19:36:16,545:INFO:Uploading model into container now
2021-01-31 19:36:16,545:INFO:create_model_container: 4
2021-01-31 19:36:16,546:INFO:master_model_container: 4
2021-01-31 19:36:16,546:INFO:display_container: 2
2021-01-31 19:36:16,549:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=123, splitter='best')
2021-01-31 19:36:16,549:INFO:create_model() succesfully completed......................................
2021-01-31 19:36:16,950:INFO:SubProcess create_model() end ==================================
2021-01-31 19:36:16,951:INFO:Creating metrics dataframe
2021-01-31 19:36:16,997:INFO:Initializing SVM - Linear Kernel
2021-01-31 19:36:16,997:INFO:Total runtime is 3.5056967337926226 minutes
2021-01-31 19:36:17,017:INFO:SubProcess create_model() called ==================================
2021-01-31 19:36:17,018:INFO:Initializing create_model()
2021-01-31 19:36:17,018:INFO:create_model(estimator=svm, fold=StratifiedKFold(n_splits=10, random_state=123, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7f1a03afa2e0>, kwargs={})
2021-01-31 19:36:17,018:INFO:Checking exceptions
2021-01-31 19:36:17,018:INFO:Importing libraries
2021-01-31 19:36:17,018:INFO:Copying training dataset
2021-01-31 19:36:17,066:INFO:Defining folds
2021-01-31 19:36:17,067:INFO:Declaring metric variables
2021-01-31 19:36:17,087:INFO:Importing untrained model
2021-01-31 19:36:17,115:INFO:SVM - Linear Kernel Imported succesfully
2021-01-31 19:36:17,168:INFO:Starting cross validation
2021-01-31 19:36:17,170:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=123, shuffle=False), n_jobs=-1
2021-01-31 19:42:35,369:WARNING:create_model() for svm raised an exception or returned all 0.0, trying without fit_kwargs:
2021-01-31 19:42:35,403:WARNING:Traceback (most recent call last):
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 2141, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 3090, in create_model_supervised
    scores = cross_validate(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 242, in cross_validate
    scores = parallel(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/parallel.py", line 1061, in __call__
    self.retrieve()
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/parallel.py", line 940, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 434, in result
    self._condition.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt

2021-01-31 19:42:35,405:INFO:Initializing create_model()
2021-01-31 19:42:35,405:INFO:create_model(estimator=svm, fold=StratifiedKFold(n_splits=10, random_state=123, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7f1a03afa2e0>, kwargs={})
2021-01-31 19:42:35,405:INFO:Checking exceptions
2021-01-31 19:42:35,405:INFO:Importing libraries
2021-01-31 19:42:35,405:INFO:Copying training dataset
2021-01-31 19:42:35,471:INFO:Defining folds
2021-01-31 19:42:35,471:INFO:Declaring metric variables
2021-01-31 19:42:35,504:INFO:Importing untrained model
2021-01-31 19:42:35,535:INFO:SVM - Linear Kernel Imported succesfully
2021-01-31 19:42:35,573:ERROR:create_model() for svm raised an exception:
2021-01-31 19:42:35,659:ERROR:Traceback (most recent call last):
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 2141, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 3090, in create_model_supervised
    scores = cross_validate(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 242, in cross_validate
    scores = parallel(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/parallel.py", line 1061, in __call__
    self.retrieve()
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/parallel.py", line 940, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 434, in result
    self._condition.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 2161, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 3061, in create_model_supervised
    display.update_monitor(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/Display.py", line 90, in update_monitor
    self.display_monitor()
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/Display.py", line 66, in display_monitor
    self._update_display(self.monitor, display_id=self.monitor_id)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/Display.py", line 137, in _update_display
    return update_display(df, *args, **kwargs)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/core/display.py", line 343, in update_display
    display(obj, display_id=display_id, **kwargs)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/core/display.py", line 313, in display
    format_dict, md_dict = format(obj, include=include, exclude=exclude)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/core/formatters.py", line 180, in format
    data = formatter(obj)
  File "<decorator-gen-10>", line 2, in __call__
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/core/formatters.py", line 224, in catch_format_error
    r = method(self, *args, **kwargs)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/core/formatters.py", line 702, in __call__
    printer.pretty(obj)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/lib/pretty.py", line 394, in pretty
    return _repr_pprint(obj, self, cycle)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/lib/pretty.py", line 700, in _repr_pprint
    output = repr(obj)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/core/frame.py", line 744, in __repr__
    self.to_string(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/core/frame.py", line 883, in to_string
    return formatter.to_string(buf=buf, encoding=encoding)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/io/formats/format.py", line 921, in to_string
    return self.get_result(buf=buf, encoding=encoding)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/io/formats/format.py", line 520, in get_result
    self.write_result(buf=f)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/io/formats/format.py", line 834, in write_result
    strcols = self._to_str_columns()
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/io/formats/format.py", line 737, in _to_str_columns
    str_index = self._get_formatted_index(frame)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1065, in _get_formatted_index
    fmt_index = [index.format(name=self.show_row_idx_names, formatter=fmt)]
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 929, in format
    return self._format_with_header(header, na_rep=na_rep)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 945, in _format_with_header
    mask = isna(values)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/core/dtypes/missing.py", line 124, in isna
    return _isna(obj)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/core/dtypes/missing.py", line 157, in _isna
    return _isna_ndarraylike(obj, inf_as_na=inf_as_na)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/core/dtypes/missing.py", line 217, in _isna_ndarraylike
    elif is_string_dtype(dtype):
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/core/dtypes/common.py", line 605, in is_string_dtype
    return _is_dtype(arr_or_dtype, condition)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/core/dtypes/common.py", line 1541, in _is_dtype
    def _is_dtype(arr_or_dtype, condition) -> bool:
KeyboardInterrupt

2021-01-31 19:42:35,662:INFO:Initializing Ridge Classifier
2021-01-31 19:42:35,662:INFO:Total runtime is 9.816778874397277 minutes
2021-01-31 19:42:35,716:INFO:SubProcess create_model() called ==================================
2021-01-31 19:42:35,717:INFO:Initializing create_model()
2021-01-31 19:42:35,717:INFO:create_model(estimator=ridge, fold=StratifiedKFold(n_splits=10, random_state=123, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7f1a03afa2e0>, kwargs={})
2021-01-31 19:42:35,718:INFO:Checking exceptions
2021-01-31 19:42:35,718:INFO:Importing libraries
2021-01-31 19:42:35,718:INFO:Copying training dataset
2021-01-31 19:42:35,801:INFO:Defining folds
2021-01-31 19:42:35,802:INFO:Declaring metric variables
2021-01-31 19:42:35,841:INFO:Importing untrained model
2021-01-31 19:42:35,879:INFO:Ridge Classifier Imported succesfully
2021-01-31 19:42:35,947:INFO:Starting cross validation
2021-01-31 19:42:35,949:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=123, shuffle=False), n_jobs=-1
2021-01-31 19:42:37,246:WARNING:create_model() for ridge raised an exception or returned all 0.0, trying without fit_kwargs:
2021-01-31 19:42:37,248:WARNING:Traceback (most recent call last):
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 2141, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 3090, in create_model_supervised
    scores = cross_validate(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 242, in cross_validate
    scores = parallel(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/parallel.py", line 1061, in __call__
    self.retrieve()
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/parallel.py", line 940, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 434, in result
    self._condition.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt

2021-01-31 19:42:37,249:INFO:Initializing create_model()
2021-01-31 19:42:37,249:INFO:create_model(estimator=ridge, fold=StratifiedKFold(n_splits=10, random_state=123, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7f1a03afa2e0>, kwargs={})
2021-01-31 19:42:37,249:INFO:Checking exceptions
2021-01-31 19:42:37,249:INFO:Importing libraries
2021-01-31 19:42:37,250:INFO:Copying training dataset
2021-01-31 19:42:37,334:INFO:Defining folds
2021-01-31 19:42:37,335:INFO:Declaring metric variables
2021-01-31 19:42:37,385:INFO:Importing untrained model
2021-01-31 19:42:37,427:INFO:Ridge Classifier Imported succesfully
2021-01-31 19:42:37,518:INFO:Starting cross validation
2021-01-31 19:42:37,521:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=123, shuffle=False), n_jobs=-1
2021-01-31 19:42:38,972:ERROR:create_model() for ridge raised an exception:
2021-01-31 19:42:38,975:ERROR:Traceback (most recent call last):
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 2141, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 3090, in create_model_supervised
    scores = cross_validate(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 242, in cross_validate
    scores = parallel(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/parallel.py", line 1061, in __call__
    self.retrieve()
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/parallel.py", line 940, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 434, in result
    self._condition.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 2161, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 3090, in create_model_supervised
    scores = cross_validate(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 242, in cross_validate
    scores = parallel(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/parallel.py", line 1061, in __call__
    self.retrieve()
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/parallel.py", line 940, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 434, in result
    self._condition.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt

2021-01-31 19:42:38,977:INFO:Initializing Random Forest Classifier
2021-01-31 19:42:38,978:INFO:Total runtime is 9.87203246752421 minutes
2021-01-31 19:42:39,022:INFO:SubProcess create_model() called ==================================
2021-01-31 19:42:39,024:INFO:Initializing create_model()
2021-01-31 19:42:39,025:INFO:create_model(estimator=rf, fold=StratifiedKFold(n_splits=10, random_state=123, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7f1a03afa2e0>, kwargs={})
2021-01-31 19:42:39,025:INFO:Checking exceptions
2021-01-31 19:42:39,025:INFO:Importing libraries
2021-01-31 19:42:39,025:INFO:Copying training dataset
2021-01-31 19:42:39,121:INFO:Defining folds
2021-01-31 19:42:39,122:INFO:Declaring metric variables
2021-01-31 19:42:39,162:INFO:Importing untrained model
2021-01-31 19:42:39,202:INFO:Random Forest Classifier Imported succesfully
2021-01-31 19:42:39,266:INFO:Starting cross validation
2021-01-31 19:42:39,269:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=123, shuffle=False), n_jobs=-1
2021-01-31 19:42:41,578:WARNING:create_model() for rf raised an exception or returned all 0.0, trying without fit_kwargs:
2021-01-31 19:42:41,580:WARNING:Traceback (most recent call last):
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 2141, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 3090, in create_model_supervised
    scores = cross_validate(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 242, in cross_validate
    scores = parallel(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/parallel.py", line 1061, in __call__
    self.retrieve()
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/parallel.py", line 940, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 434, in result
    self._condition.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt

2021-01-31 19:42:41,582:INFO:Initializing create_model()
2021-01-31 19:42:41,582:INFO:create_model(estimator=rf, fold=StratifiedKFold(n_splits=10, random_state=123, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7f1a03afa2e0>, kwargs={})
2021-01-31 19:42:41,583:INFO:Checking exceptions
2021-01-31 19:42:41,583:INFO:Importing libraries
2021-01-31 19:42:41,584:INFO:Copying training dataset
2021-01-31 19:42:41,661:INFO:Defining folds
2021-01-31 19:42:41,663:INFO:Declaring metric variables
2021-01-31 19:42:41,704:INFO:Importing untrained model
2021-01-31 19:42:41,745:INFO:Random Forest Classifier Imported succesfully
2021-01-31 19:42:41,812:INFO:Starting cross validation
2021-01-31 19:42:41,817:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=123, shuffle=False), n_jobs=-1
2021-01-31 19:42:43,444:ERROR:create_model() for rf raised an exception:
2021-01-31 19:42:43,445:ERROR:Traceback (most recent call last):
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 2141, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 3090, in create_model_supervised
    scores = cross_validate(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 242, in cross_validate
    scores = parallel(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/parallel.py", line 1061, in __call__
    self.retrieve()
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/parallel.py", line 940, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 434, in result
    self._condition.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 2161, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 3090, in create_model_supervised
    scores = cross_validate(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 242, in cross_validate
    scores = parallel(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/parallel.py", line 1061, in __call__
    self.retrieve()
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/parallel.py", line 940, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 434, in result
    self._condition.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt

2021-01-31 19:42:43,449:INFO:Initializing Quadratic Discriminant Analysis
2021-01-31 19:42:43,450:INFO:Total runtime is 9.94656929175059 minutes
2021-01-31 19:42:43,490:INFO:SubProcess create_model() called ==================================
2021-01-31 19:42:43,492:INFO:Initializing create_model()
2021-01-31 19:42:43,492:INFO:create_model(estimator=qda, fold=StratifiedKFold(n_splits=10, random_state=123, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7f1a03afa2e0>, kwargs={})
2021-01-31 19:42:43,492:INFO:Checking exceptions
2021-01-31 19:42:43,493:INFO:Importing libraries
2021-01-31 19:42:43,493:INFO:Copying training dataset
2021-01-31 19:42:43,592:INFO:Defining folds
2021-01-31 19:42:43,594:INFO:Declaring metric variables
2021-01-31 19:42:43,630:WARNING:create_model() for qda raised an exception or returned all 0.0, trying without fit_kwargs:
2021-01-31 19:42:43,654:WARNING:Traceback (most recent call last):
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 2141, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 2968, in create_model_supervised
    display.display_monitor()
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/Display.py", line 66, in display_monitor
    self._update_display(self.monitor, display_id=self.monitor_id)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/Display.py", line 137, in _update_display
    return update_display(df, *args, **kwargs)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/core/display.py", line 343, in update_display
    display(obj, display_id=display_id, **kwargs)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/core/display.py", line 313, in display
    format_dict, md_dict = format(obj, include=include, exclude=exclude)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/core/formatters.py", line 180, in format
    data = formatter(obj)
  File "<decorator-gen-9>", line 2, in __call__
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/core/formatters.py", line 224, in catch_format_error
    r = method(self, *args, **kwargs)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/core/formatters.py", line 345, in __call__
    return method()
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/core/frame.py", line 798, in _repr_html_
    return formatter.to_html(notebook=True)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/io/formats/format.py", line 988, in to_html
    return Klass(self, classes=classes, border=border).get_result(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/io/formats/format.py", line 520, in get_result
    self.write_result(buf=f)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/io/formats/html.py", line 203, in write_result
    buffer_put_lines(buf, self.render())
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/io/formats/html.py", line 607, in render
    super().render()
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/io/formats/html.py", line 192, in render
    self._write_table()
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/io/formats/html.py", line 231, in _write_table
    self._write_header(indent + self.indent_delta)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/io/formats/html.py", line 365, in _write_header
    self._write_col_header(indent + self.indent_delta)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/io/formats/html.py", line 345, in _write_col_header
    row.extend(self._get_columns_formatted_values())
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/io/formats/html.py", line 574, in _get_columns_formatted_values
    return self.columns.format()
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 929, in format
    return self._format_with_header(header, na_rep=na_rep)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 939, in _format_with_header
    values = lib.maybe_convert_objects(values, safe=1)
  File "pandas/_libs/lib.pyx", line 2118, in pandas._libs.lib.maybe_convert_objects
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/numpy/core/numeric.py", line 268, in full
    @set_module('numpy')
KeyboardInterrupt

2021-01-31 19:42:43,655:INFO:Initializing create_model()
2021-01-31 19:42:43,656:INFO:create_model(estimator=qda, fold=StratifiedKFold(n_splits=10, random_state=123, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7f1a03afa2e0>, kwargs={})
2021-01-31 19:42:43,656:INFO:Checking exceptions
2021-01-31 19:42:43,657:INFO:Importing libraries
2021-01-31 19:42:43,657:INFO:Copying training dataset
2021-01-31 19:42:43,746:INFO:Defining folds
2021-01-31 19:42:43,747:INFO:Declaring metric variables
2021-01-31 19:42:43,779:INFO:Importing untrained model
2021-01-31 19:42:43,811:INFO:Quadratic Discriminant Analysis Imported succesfully
2021-01-31 19:42:43,892:INFO:Starting cross validation
2021-01-31 19:42:43,895:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=123, shuffle=False), n_jobs=-1
2021-01-31 19:42:44,193:ERROR:create_model() for qda raised an exception:
2021-01-31 19:42:44,234:ERROR:Traceback (most recent call last):
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 2141, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 2968, in create_model_supervised
    display.display_monitor()
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/Display.py", line 66, in display_monitor
    self._update_display(self.monitor, display_id=self.monitor_id)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/Display.py", line 137, in _update_display
    return update_display(df, *args, **kwargs)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/core/display.py", line 343, in update_display
    display(obj, display_id=display_id, **kwargs)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/core/display.py", line 313, in display
    format_dict, md_dict = format(obj, include=include, exclude=exclude)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/core/formatters.py", line 180, in format
    data = formatter(obj)
  File "<decorator-gen-9>", line 2, in __call__
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/core/formatters.py", line 224, in catch_format_error
    r = method(self, *args, **kwargs)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/core/formatters.py", line 345, in __call__
    return method()
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/core/frame.py", line 798, in _repr_html_
    return formatter.to_html(notebook=True)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/io/formats/format.py", line 988, in to_html
    return Klass(self, classes=classes, border=border).get_result(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/io/formats/format.py", line 520, in get_result
    self.write_result(buf=f)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/io/formats/html.py", line 203, in write_result
    buffer_put_lines(buf, self.render())
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/io/formats/html.py", line 607, in render
    super().render()
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/io/formats/html.py", line 192, in render
    self._write_table()
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/io/formats/html.py", line 231, in _write_table
    self._write_header(indent + self.indent_delta)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/io/formats/html.py", line 365, in _write_header
    self._write_col_header(indent + self.indent_delta)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/io/formats/html.py", line 345, in _write_col_header
    row.extend(self._get_columns_formatted_values())
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/io/formats/html.py", line 574, in _get_columns_formatted_values
    return self.columns.format()
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 929, in format
    return self._format_with_header(header, na_rep=na_rep)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 939, in _format_with_header
    values = lib.maybe_convert_objects(values, safe=1)
  File "pandas/_libs/lib.pyx", line 2118, in pandas._libs.lib.maybe_convert_objects
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/numpy/core/numeric.py", line 268, in full
    @set_module('numpy')
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 2161, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 3090, in create_model_supervised
    scores = cross_validate(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 242, in cross_validate
    scores = parallel(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/parallel.py", line 1048, in __call__
    if self.dispatch_one_batch(iterator):
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/parallel.py", line 866, in dispatch_one_batch
    self._dispatch(tasks)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/parallel.py", line 784, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 531, in apply_async
    future = self._workers.submit(SafeFunction(func))
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/externals/loky/reusable_executor.py", line 177, in submit
    return super(_ReusablePoolExecutor, self).submit(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 1122, in submit
    self._ensure_executor_running()
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 1096, in _ensure_executor_running
    self._adjust_process_count()
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 1074, in _adjust_process_count
    worker_exit_lock = self._context.BoundedSemaphore(1)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/externals/loky/backend/context.py", line 319, in BoundedSemaphore
    def BoundedSemaphore(self, value):
KeyboardInterrupt

2021-01-31 19:42:44,238:INFO:Initializing Ada Boost Classifier
2021-01-31 19:42:44,240:INFO:Total runtime is 9.959733390808106 minutes
2021-01-31 19:42:44,286:INFO:SubProcess create_model() called ==================================
2021-01-31 19:42:44,287:INFO:Initializing create_model()
2021-01-31 19:42:44,288:INFO:create_model(estimator=ada, fold=StratifiedKFold(n_splits=10, random_state=123, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7f1a03afa2e0>, kwargs={})
2021-01-31 19:42:44,288:INFO:Checking exceptions
2021-01-31 19:42:44,288:INFO:Importing libraries
2021-01-31 19:42:44,289:INFO:Copying training dataset
2021-01-31 19:42:44,386:INFO:Defining folds
2021-01-31 19:42:44,387:INFO:Declaring metric variables
2021-01-31 19:42:44,422:INFO:Importing untrained model
2021-01-31 19:42:44,438:WARNING:create_model() for ada raised an exception or returned all 0.0, trying without fit_kwargs:
2021-01-31 19:42:44,454:WARNING:Traceback (most recent call last):
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 2141, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 2992, in create_model_supervised
    display.update_monitor(2, full_name)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/Display.py", line 90, in update_monitor
    self.display_monitor()
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/Display.py", line 66, in display_monitor
    self._update_display(self.monitor, display_id=self.monitor_id)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/Display.py", line 137, in _update_display
    return update_display(df, *args, **kwargs)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/core/display.py", line 343, in update_display
    display(obj, display_id=display_id, **kwargs)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/core/display.py", line 320, in display
    publish_display_data(data=format_dict, metadata=md_dict, **kwargs)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/core/display.py", line 119, in publish_display_data
    display_pub.publish(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/ipykernel/zmqshell.py", line 112, in publish
    self._flush_streams()
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/ipykernel/zmqshell.py", line 79, in _flush_streams
    sys.stdout.flush()
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/ipykernel/iostream.py", line 352, in flush
    if not evt.wait(self.flush_timeout):
  File "/usr/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt

2021-01-31 19:42:44,455:INFO:Initializing create_model()
2021-01-31 19:42:44,456:INFO:create_model(estimator=ada, fold=StratifiedKFold(n_splits=10, random_state=123, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7f1a03afa2e0>, kwargs={})
2021-01-31 19:42:44,456:INFO:Checking exceptions
2021-01-31 19:42:44,457:INFO:Importing libraries
2021-01-31 19:42:44,457:INFO:Copying training dataset
2021-01-31 19:42:44,547:INFO:Defining folds
2021-01-31 19:42:44,548:INFO:Declaring metric variables
2021-01-31 19:42:44,585:INFO:Importing untrained model
2021-01-31 19:42:44,622:INFO:Ada Boost Classifier Imported succesfully
2021-01-31 19:42:44,677:ERROR:create_model() for ada raised an exception:
2021-01-31 19:42:44,686:ERROR:Traceback (most recent call last):
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 2141, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 2992, in create_model_supervised
    display.update_monitor(2, full_name)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/Display.py", line 90, in update_monitor
    self.display_monitor()
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/Display.py", line 66, in display_monitor
    self._update_display(self.monitor, display_id=self.monitor_id)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/Display.py", line 137, in _update_display
    return update_display(df, *args, **kwargs)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/core/display.py", line 343, in update_display
    display(obj, display_id=display_id, **kwargs)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/core/display.py", line 320, in display
    publish_display_data(data=format_dict, metadata=md_dict, **kwargs)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/core/display.py", line 119, in publish_display_data
    display_pub.publish(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/ipykernel/zmqshell.py", line 112, in publish
    self._flush_streams()
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/ipykernel/zmqshell.py", line 79, in _flush_streams
    sys.stdout.flush()
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/ipykernel/iostream.py", line 352, in flush
    if not evt.wait(self.flush_timeout):
  File "/usr/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 2161, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 3061, in create_model_supervised
    display.update_monitor(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/Display.py", line 90, in update_monitor
    self.display_monitor()
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/Display.py", line 66, in display_monitor
    self._update_display(self.monitor, display_id=self.monitor_id)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/Display.py", line 137, in _update_display
    return update_display(df, *args, **kwargs)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/core/display.py", line 343, in update_display
    display(obj, display_id=display_id, **kwargs)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/core/display.py", line 313, in display
    format_dict, md_dict = format(obj, include=include, exclude=exclude)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/core/formatters.py", line 180, in format
    data = formatter(obj)
  File "<decorator-gen-9>", line 2, in __call__
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/core/formatters.py", line 224, in catch_format_error
    r = method(self, *args, **kwargs)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/core/formatters.py", line 345, in __call__
    return method()
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/core/frame.py", line 798, in _repr_html_
    return formatter.to_html(notebook=True)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/io/formats/format.py", line 988, in to_html
    return Klass(self, classes=classes, border=border).get_result(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/io/formats/format.py", line 520, in get_result
    self.write_result(buf=f)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/io/formats/html.py", line 203, in write_result
    buffer_put_lines(buf, self.render())
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/io/formats/html.py", line 607, in render
    super().render()
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/io/formats/html.py", line 192, in render
    self._write_table()
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/io/formats/html.py", line 233, in _write_table
    self._write_body(indent + self.indent_delta)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/io/formats/html.py", line 379, in _write_body
    fmt_values = self._get_formatted_values()
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/io/formats/html.py", line 571, in _get_formatted_values
    return {i: self.fmt._format_col(i) for i in range(self.ncols)}
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/io/formats/html.py", line 571, in <dictcomp>
    return {i: self.fmt._format_col(i) for i in range(self.ncols)}
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/io/formats/format.py", line 954, in _format_col
    return format_array(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1179, in format_array
    return fmt_obj.get_result()
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1210, in get_result
    fmt_values = self._format_strings()
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1265, in _format_strings
    for i, v in enumerate(vals):
KeyboardInterrupt

2021-01-31 19:42:44,690:INFO:Initializing Gradient Boosting Classifier
2021-01-31 19:42:44,690:INFO:Total runtime is 9.967236391703288 minutes
2021-01-31 19:42:44,738:INFO:SubProcess create_model() called ==================================
2021-01-31 19:42:44,744:INFO:Initializing create_model()
2021-01-31 19:42:44,749:INFO:create_model(estimator=gbc, fold=StratifiedKFold(n_splits=10, random_state=123, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7f1a03afa2e0>, kwargs={})
2021-01-31 19:42:44,752:INFO:Checking exceptions
2021-01-31 19:42:44,753:INFO:Importing libraries
2021-01-31 19:42:44,753:INFO:Copying training dataset
2021-01-31 19:42:44,879:INFO:Defining folds
2021-01-31 19:42:44,879:INFO:Declaring metric variables
2021-01-31 19:42:44,928:INFO:Importing untrained model
2021-01-31 19:42:44,961:WARNING:create_model() for gbc raised an exception or returned all 0.0, trying without fit_kwargs:
2021-01-31 19:42:45,003:WARNING:Traceback (most recent call last):
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 2141, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 2993, in create_model_supervised
    display.display_monitor()
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/Display.py", line 66, in display_monitor
    self._update_display(self.monitor, display_id=self.monitor_id)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/Display.py", line 137, in _update_display
    return update_display(df, *args, **kwargs)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/core/display.py", line 343, in update_display
    display(obj, display_id=display_id, **kwargs)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/core/display.py", line 313, in display
    format_dict, md_dict = format(obj, include=include, exclude=exclude)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/core/formatters.py", line 180, in format
    data = formatter(obj)
  File "<decorator-gen-9>", line 2, in __call__
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/core/formatters.py", line 224, in catch_format_error
    r = method(self, *args, **kwargs)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/core/formatters.py", line 343, in __call__
    method = get_real_method(obj, self.print_method)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/utils/dir2.py", line 65, in get_real_method
    canary = getattr(obj, '_ipython_canary_method_should_not_exist_', None)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/core/generic.py", line 5141, in __getattr__
    return object.__getattribute__(self, name)
KeyboardInterrupt

2021-01-31 19:42:45,005:INFO:Initializing create_model()
2021-01-31 19:42:45,005:INFO:create_model(estimator=gbc, fold=StratifiedKFold(n_splits=10, random_state=123, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7f1a03afa2e0>, kwargs={})
2021-01-31 19:42:45,006:INFO:Checking exceptions
2021-01-31 19:42:45,006:INFO:Importing libraries
2021-01-31 19:42:45,006:INFO:Copying training dataset
2021-01-31 19:42:45,099:INFO:Defining folds
2021-01-31 19:42:45,101:INFO:Declaring metric variables
2021-01-31 19:42:45,140:INFO:Importing untrained model
2021-01-31 19:42:45,175:INFO:Gradient Boosting Classifier Imported succesfully
2021-01-31 19:42:45,235:INFO:Starting cross validation
2021-01-31 19:42:45,237:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=123, shuffle=False), n_jobs=-1
2021-01-31 19:42:45,677:ERROR:create_model() for gbc raised an exception:
2021-01-31 19:42:45,679:ERROR:Traceback (most recent call last):
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 2141, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 2993, in create_model_supervised
    display.display_monitor()
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/Display.py", line 66, in display_monitor
    self._update_display(self.monitor, display_id=self.monitor_id)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/Display.py", line 137, in _update_display
    return update_display(df, *args, **kwargs)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/core/display.py", line 343, in update_display
    display(obj, display_id=display_id, **kwargs)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/core/display.py", line 313, in display
    format_dict, md_dict = format(obj, include=include, exclude=exclude)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/core/formatters.py", line 180, in format
    data = formatter(obj)
  File "<decorator-gen-9>", line 2, in __call__
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/core/formatters.py", line 224, in catch_format_error
    r = method(self, *args, **kwargs)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/core/formatters.py", line 343, in __call__
    method = get_real_method(obj, self.print_method)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/IPython/utils/dir2.py", line 65, in get_real_method
    canary = getattr(obj, '_ipython_canary_method_should_not_exist_', None)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pandas/core/generic.py", line 5141, in __getattr__
    return object.__getattribute__(self, name)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 2161, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 3090, in create_model_supervised
    scores = cross_validate(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 242, in cross_validate
    scores = parallel(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/parallel.py", line 1051, in __call__
    while self.dispatch_one_batch(iterator):
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/parallel.py", line 866, in dispatch_one_batch
    self._dispatch(tasks)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/parallel.py", line 784, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 531, in apply_async
    future = self._workers.submit(SafeFunction(func))
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/externals/loky/reusable_executor.py", line 177, in submit
    return super(_ReusablePoolExecutor, self).submit(
  File "/homelab/ta/code/FinalProjectEnv/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 1102, in submit
    raise self._flags.broken
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {EXIT(1), SIGINT(-2), EXIT(1)}

2021-01-31 19:42:45,680:INFO:Initializing Linear Discriminant Analysis
2021-01-31 19:42:45,680:INFO:Total runtime is 9.983745416005453 minutes
2021-01-31 19:42:45,819:INFO:SubProcess create_model() called ==================================
2021-01-31 19:42:45,822:INFO:Initializing create_model()
2021-01-31 19:42:45,823:INFO:create_model(estimator=lda, fold=StratifiedKFold(n_splits=10, random_state=123, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7f1a03afa2e0>, kwargs={})
2021-01-31 19:42:45,823:INFO:Checking exceptions
2021-01-31 19:42:45,823:INFO:Importing libraries
2021-01-31 19:42:45,824:INFO:Copying training dataset
2021-01-31 19:42:45,973:INFO:Defining folds
2021-01-31 19:42:45,974:INFO:Declaring metric variables
2021-01-31 19:42:46,032:INFO:Importing untrained model
2021-01-31 19:42:46,116:INFO:Linear Discriminant Analysis Imported succesfully
2021-01-31 19:42:46,213:INFO:Starting cross validation
2021-01-31 19:42:46,216:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=123, shuffle=False), n_jobs=-1
